name: CI/CD Pipeline
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Reinstall npm
        run: npm install -g npm@latest

      - name: Setup Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '14.21.13'
          npm : '6.14.8'
          python-version: '2.7' 

      - name: Install Build Essential
        run: |
              sudo apt-get update
              sudo apt-get install -y build-essential

      - name: Install Python 2.7
        run: |
             sudo apt-get install python2.7
             sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1

      - name: Clean npm cache
        run: npm cache clean --force
          
      - name: Install dependencies
        run: |
           npm install npm@latest
           npm install 
           
          
      - name: Build
        run: npm run build

      - name: Deploy to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: |
          aws s3 sync build/ s3://techdome-jenkins-cicd-bucket/
          aws cloudfront create-invalidation --distribution-id E1IUL1R5EKH6RA --paths "/*"
